# Generated by Django 4.1.2 on 2022-10-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangSua',
            fields=[
                ('ma_hang_sua', models.CharField(db_column='Ma_hang_sua', max_length=20, primary_key=True, serialize=False)),
                ('ten_hang_sua', models.CharField(db_column='Ten_hang_sua', max_length=100)),
                ('dia_chi', models.CharField(db_column='Dia_chi', max_length=200)),
                ('dien_thoai', models.CharField(db_column='Dien_thoai', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=100)),
            ],
            options={
                'db_table': 'hang_sua',
                'managed': False,
            },
        ),
    ]
