# Generated by Django 4.1.2 on 2022-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlbansua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSua',
            fields=[
                ('ma_loai_sua', models.CharField(db_column='Ma_loai_sua', max_length=3, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(db_column='Ten_loai', max_length=50)),
            ],
            options={
                'db_table': 'loai_sua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sua',
            fields=[
                ('ma_sua', models.CharField(db_column='Ma_sua', max_length=6, primary_key=True, serialize=False)),
                ('ten_sua', models.CharField(db_column='Ten_sua', max_length=100)),
                ('trong_luong', models.IntegerField(db_column='Trong_luong')),
                ('don_gia', models.IntegerField(db_column='Don_gia')),
                ('tp_dinh_duong', models.TextField(db_column='Tp_dinh_duong')),
                ('loi_ich', models.TextField(db_column='Loi_ich')),
                ('hinh', models.CharField(db_column='Hinh', max_length=200)),
            ],
            options={
                'db_table': 'sua',
                'managed': False,
            },
        ),
    ]
